"""
EmailAddressMother module.
"""

import string
from random import choice, choices, randint, shuffle
from sys import version_info
from typing import List, Optional, assert_never

if version_info >= (3, 12):
    from typing import override  # pragma: no cover
else:
    from typing_extensions import override  # pragma: no cover

from object_mother_pattern.mothers import StringCase, StringMother
from object_mother_pattern.mothers.base_mother import BaseMother

from .domain_mother import DomainMother


class EmailAddressMother(BaseMother[str]):
    """
    EmailAddressMother class is responsible for creating random email address values.

    Example:
    ```python
    from object_mother_pattern.mothers.internet import EmailAddressMother

    email_address = EmailAddressMother.create()
    print(email_address)
    # >>> user.name123@example.com
    ```
    """

    _type: type = str

    @classmethod
    @override
    def create(  # noqa: C901, PLR0912, PLR0915
        cls,
        *,
        value: Optional[str] = None,
        min_length: int = 6,  # e.g., a@b.io (6 chars)
        max_length: int = 254,  # RFC 5321 limit
        domain: Optional[str] = None,
        string_case: Optional[StringCase] = None,
        include_numbers_in_local_part: bool = True,
        allowed_special_chars_in_local_part: Optional[List[str]] = None,
    ) -> str:
        """
        Create a random email address value. If a specific email address value is provided via `value`, it is returned
        after validation. Otherwise, a random email address value is generated.

        The local part will be between 1 and 64 characters, contain lowercase letters (a-z),
        and optionally numbers and specified special characters.
        The domain part is generated by `DomainMother` or can be provided.
        The total email length will be between `min_length` and `max_length`.

        Args:
            value (str | None, optional): Specific value to return. Defaults to None.
            min_length (int, optional): The minimum length of the email address. Must be >= 5. Defaults to 6.
            max_length (int, optional): The maximum length of the email address. Must be <= 254 and >= `min_length`.
                                        Defaults to 254.
            domain (str | None, optional): The domain of the email address. If None, a random one is generated.
                                           Defaults to None.
            string_case (StringCase | None, optional): The case of the email address. If None, a random case is chosen.
                                                       Affects both local part and domain generation. Defaults to None.
            include_numbers_in_local_part (bool, optional): Whether to include numbers (0-9) in the local part.
                                                            Defaults to True.
            allowed_special_chars_in_local_part (list[str] | None, optional): A list of special characters allowed in
                                                                             the local part. Defaults to ['.', '+'].
                                                                             Note: RFC 5322 allows others like !#$%&'*-/=?^_`{|}~

        Raises:
            TypeError: If any parameter has an invalid type.
            ValueError: If length constraints are impossible or invalid.
            ValueError: If a valid email cannot be generated after multiple attempts.

        Returns:
            str: A randomly generated email address value with the provided constraints.

        Example:
        ```python
        from object_mother_pattern.mothers import StringCase
        from object_mother_pattern.mothers.internet import EmailAddressMother

        # Random email
        email1 = EmailAddressMother.create()
        print(email1)
        # Example output: "user.123@example-domain.com"

        # Email with specific domain and case
        email2 = EmailAddressMother.create(domain='mydomain.org', string_case=StringCase.UPPERCASE)
        print(email2)
        # Example output: "LOCAL.PART@MYDOMAIN.ORG"

        # Email without numbers or special chars in local part
        email3 = EmailAddressMother.create(
        include_numbers_in_local_part=False,
        allowed_special_chars_in_local_part=[]
        )
        print(email3)
        # Example output: "anotheruser@someprovider.net"
        ```
        """
        if value is not None:
            if not isinstance(value, str):
                raise TypeError(f'{cls.__name__}: value must be a string.')
            # Basic validation for provided email value could be added here
            # For now, assume if 'value' is provided, it's a valid email.
            return value

        if not isinstance(min_length, int):
            raise TypeError(f'{cls.__name__}: min_length must be an integer.')
        if not isinstance(max_length, int):
            raise TypeError(f'{cls.__name__}: max_length must be an integer.')
        if min_length < 5:  # Smallest: a@b.c
            raise ValueError(f'{cls.__name__}: min_length must be at least 5.')
        if max_length > 254:
            raise ValueError(f'{cls.__name__}: max_length must be at most 254.')
        if min_length > max_length:
            raise ValueError(f'{cls.__name__}: min_length must be less than or equal to max_length.')

        if string_case is None:
            string_case = StringCase(value=choice(seq=tuple(StringCase)))  # noqa: S311
        if not isinstance(string_case, StringCase):
            raise TypeError(f'{cls.__name__}: string_case must be a StringCase.')

        if not isinstance(include_numbers_in_local_part, bool):
            raise TypeError(f'{cls.__name__}: include_numbers_in_local_part must be a boolean.')

        if allowed_special_chars_in_local_part is None:
            allowed_special_chars_in_local_part = ['.', '+']
        if not isinstance(allowed_special_chars_in_local_part, list) or \
           not all(isinstance(char, str) for char in allowed_special_chars_in_local_part):
            raise TypeError(f'{cls.__name__}: allowed_special_chars_in_local_part must be a list of strings.')

        # Handle domain part
        if domain is not None:
            if not isinstance(domain, str):
                raise TypeError(f'{cls.__name__}: domain must be a string.')
            # Potentially validate provided domain format here if needed
        else:
            # Calculate constraints for DomainMother
            # Max domain length: 253. Min local part: 1. Min domain: 3 (e.g. x.y)
            domain_max_len = min(253, max_length - 1 - 1)  # max_email_len - len('@') - min_local_len
            domain_min_len = max(3, min_length - 1 - 64)   # min_email_len - len('@') - max_local_len

            if domain_min_len <= 0: # Ensure domain_min_len is at least 3 for typical domains (e.g. a.b)
                domain_min_len = 3
            if domain_min_len > domain_max_len:
                raise ValueError(
                    f'{cls.__name__}: Impossible length constraints for domain generation. '
                    f'Email min/max length ({min_length}/{max_length}) is too restrictive.'
                )
            domain = DomainMother.create(
                min_length=domain_min_len,
                max_length=domain_max_len,
                string_case=string_case  # DomainMother handles its own casing
            )
        domain_len = len(domain)

        # Calculate constraints for local part
        local_part_max_len = min(64, max_length - domain_len - 1) # -1 for '@'
        local_part_min_len = max(1, min_length - domain_len - 1) # -1 for '@'
        
        if local_part_min_len <=0: # Ensure local_part_min_len is at least 1
            local_part_min_len = 1

        if local_part_min_len > local_part_max_len:
            raise ValueError(
                f'{cls.__name__}: Impossible length constraints for local part. '
                f"Domain '{domain}' (len {domain_len}) with email min/max length ({min_length}/{max_length}) "
                f'leaves invalid range {local_part_min_len}-{local_part_max_len} for local part (must be 1-64).'
            )

        # Generate local part
        for _attempt in range(100):  # Max attempts to find a valid local part
            # Choose a random length for the local part within the allowed range
            current_local_part_len = randint(local_part_min_len, local_part_max_len)
            
            local_part_candidate = cls._generate_local_part(
                length=current_local_part_len,
                include_numbers=include_numbers_in_local_part,
                allowed_special_chars=allowed_special_chars_in_local_part,
            )

            if local_part_candidate:
                # Apply string_case to the generated (lowercase) local_part
                final_local_part = local_part_candidate
                if string_case == StringCase.UPPERCASE:
                    final_local_part = local_part_candidate.upper()
                elif string_case == StringCase.MIXEDCASE:
                    final_local_part = ''.join(
                        choice((char.upper(), char.lower())) for char in local_part_candidate # noqa: S311
                    )
                # If StringCase.LOWERCASE, it's already as generated.

                email_address = f'{final_local_part}@{domain}'

                # Final length check (should be guaranteed by construction, but as a safeguard)
                if not (min_length <= len(email_address) <= max_length):
                    continue  # pragma: no cover Should not happen if logic is correct

                return email_address

        raise ValueError(  # pragma: no cover
            f'{cls.__name__}: Could not generate a valid email address meeting all criteria after 100 attempts.'
        )

    @classmethod
    def _generate_local_part(  # noqa: C901
        cls, *, length: int, include_numbers: bool, allowed_special_chars: List[str]
    ) -> Optional[str]:
        """Helper to generate a local part of a specific length."""
        if not (1 <= length <= 64): # Should be pre-validated by caller
            return None # pragma: no cover

        lc_letters = string.ascii_lowercase
        digits = string.digits
        
        # Base pool for characters (always includes lowercase letters)
        char_pool = list(lc_letters)
        if include_numbers:
            char_pool.extend(digits)
        
        # For a few attempts to construct and validate
        for _ in range(20): # Inner retry loop for construction + validation
            if length == 0: # Should not happen if length is 1 to 64
                return "" if cls._is_valid_local_part("", include_numbers, allowed_special_chars) else None # pragma: no cover

            # Start with a guaranteed letter if no special chars are involved yet, or ensure one later
            candidate_chars = [choice(lc_letters)] if length > 0 else []

            # Fill remaining length
            if length > 1:
                fill_pool = list(char_pool) # Pool for subsequent chars
                if allowed_special_chars:
                    fill_pool.extend(allowed_special_chars) # Add special chars to the fill pool
                
                candidate_chars.extend(choices(fill_pool, k=length - 1))
                shuffle(candidate_chars) # Shuffle to make the initial letter position random

            candidate = "".join(candidate_chars)
            
            # Post-generation validation
            if cls._is_valid_local_part(
                candidate,
                include_numbers=include_numbers,
                allowed_special_chars=allowed_special_chars
            ):
                return candidate
        
        return None # Failed to generate a valid local part after inner retries

    @classmethod
    def _is_valid_local_part(
        cls, local_part: str, *, include_numbers: bool, allowed_special_chars: List[str]
    ) -> bool:
        """Validates the generated local part against RFC-like rules and specified character sets."""
        if not (1 <= len(local_part) <= 64):
            return False

        # Must contain at least one letter (a-z)
        if not any(c in string.ascii_lowercase for c in local_part):
            return False

        for char_idx, char_val in enumerate(local_part):
            is_letter = char_val in string.ascii_lowercase
            is_digit = include_numbers and char_val in string.digits
            is_allowed_special = char_val in allowed_special_chars
            
            if not (is_letter or is_digit or is_allowed_special):
                return False # Character not in allowed set

            # Rules for dot, if dot is an allowed special character
            if '.' in allowed_special_chars and char_val == '.':
                if char_idx == 0 or char_idx == len(local_part) - 1:  # Dot at start or end
                    return False
                if local_part[char_idx - 1] == '.':  # Consecutive dots ".."
                    return False
        
        return True

    @classmethod
    def invalid_value(cls) -> str:
        """
        Create an invalid email address value.

        Returns:
            str: Invalid email address string.
        """
        # An invalid email can be many things, e.g., missing '@', multiple '@@', invalid chars, etc.
        # Using StringMother.invalid_value() provides a generic invalid string.
        # Or, construct a more specific invalid email:
        options = [
            "plainaddress",  # Missing @ and domain
            "@missinglocalpart.com",
            "username@.com",  # Domain starts with dot
            "username@domain..com",  # Domain with double dot
            "username@domain.c",  # TLD too short (usually)
            "username space@domain.com", # Contains space
            StringMother.invalid_value(), # Generic invalid string
        ]
        return choice(options) # noqa: S311
