"""
This module describes several alphabets.
"""

SPECIAL_CHARS = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'  # some chars can break csv files (, ; |)
SUPER_SPECIAL_CHARS = ' £çÇñÑ¡¿'  # some chars are not accepted by some websites (contains space)

ALPHABET_LOWERCASE_BASIC = 'abcdefghijklmnopqrstuvwxyz'
ALPHABET_UPPERCASE_BASIC = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
DIGITS_BASIC = '0123456789'
ALPHABET_BASIC = ALPHABET_LOWERCASE_BASIC + ALPHABET_UPPERCASE_BASIC + DIGITS_BASIC

ALPHABET_LOWERCASE_BASE32 = 'abcdefghijklmnopqrstuvwxyz'
ALPHABET_UPPERCASE_BASE32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
DIGITS_BASE32 = '234567'
ALPHABET_BASE32 = ALPHABET_LOWERCASE_BASE32 + ALPHABET_UPPERCASE_BASE32 + DIGITS_BASE32

ALPHABET_LOWERCASE_BASE56 = 'abcdefghijkmnpqrstuvwxyz'  # without l, o
ALPHABET_UPPERCASE_BASE56 = 'ABCDEFGHJKLMNPQRSTUVWXYZ'  # without I, O
DIGITS_BASE56 = '23456789'  # without 0, 1
ALPHABET_BASE56 = ALPHABET_LOWERCASE_BASE56 + ALPHABET_UPPERCASE_BASE56 + DIGITS_BASE56

ALPHABET_LOWERCASE_BASE58 = 'abcdefghijkmnopqrstuvwxyz'  # without l
ALPHABET_UPPERCASE_BASE58 = 'ABCDEFGHJKLMNPQRSTUVWXYZ'  # without I, O
DIGITS_BASE58 = '123456789'  # without 0
ALPHABET_BASE58 = ALPHABET_LOWERCASE_BASE58 + ALPHABET_UPPERCASE_BASE58 + DIGITS_BASE58

ALPHABET_LOWERCASE_BASE64 = 'abcdefghijklmnopqrstuvwxyz'
ALPHABET_UPPERCASE_BASE64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
DIGITS_BASE64 = '0123456789'
SPECIAL_CHARACTERS_BASE64 = '+/'
ALPHABET_BASE64 = ALPHABET_LOWERCASE_BASE64 + ALPHABET_UPPERCASE_BASE64 + DIGITS_BASE64 + SPECIAL_CHARACTERS_BASE64

ALPHABET_LOWERCASE_HEXADECIMAL = 'abcdef'
ALPHABET_UPPERCASE_HEXADECIMAL = 'ABCDEF'
DIGITS_HEXADECIMAL = '0123456789'
ALPHABET_HEXADECIMAL = ALPHABET_LOWERCASE_HEXADECIMAL + ALPHABET_UPPERCASE_HEXADECIMAL + DIGITS_HEXADECIMAL
