"""
This module describes several alphabets.
"""

SPECIAL_CHARS = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'  # some chars can break csv files (, ; |)
SUPER_SPECIAL_CHARS = ' £çÇñÑ¡¿'  # some chars are not accepted by some websites (contains space)

ALPHABET_LOWERCASE_BASIC = 'abcdefghijklmnopqrstuvwxyz'
ALPHABET_UPPERCASE_BASIC = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
DIGITS_BASIC = '0123456789'
ALPHABET_BASIC = ALPHABET_LOWERCASE_BASIC + ALPHABET_UPPERCASE_BASIC + DIGITS_BASIC

ALPHABET_LOWERCASE_HEX = 'abcdef'
ALPHABET_UPPERCASE_HEX = 'ABCDEF'
DIGITS_HEX = DIGITS_BASIC
ALPHABET_HEX = ALPHABET_LOWERCASE_HEX + ALPHABET_UPPERCASE_HEX + DIGITS_HEX

ALPHABET_LOWERCASE_BASE32 = 'abcdefghijklmnopqrstuvwxyz'
ALPHABET_UPPERCASE_BASE32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
DIGITS_BASE32 = '234567'
ALPHABET_BASE32 = ALPHABET_LOWERCASE_BASE32 + ALPHABET_UPPERCASE_BASE32 + DIGITS_BASE32

ALPHABET_LOWERCASE_BASE36 = ''
ALPHABET_UPPERCASE_BASE36 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
DIGITS_BASE36 = '0123456789'
ALPHABET_BASE36 = ALPHABET_LOWERCASE_BASE36 + ALPHABET_UPPERCASE_BASE36 + DIGITS_BASE36

ALPHABET_LOWERCASE_BASE56 = 'abcdefghijkmnpqrstuvwxyz'  # without l, o
ALPHABET_UPPERCASE_BASE56 = 'ABCDEFGHJKLMNPQRSTUVWXYZ'  # without I, O
DIGITS_BASE56 = '23456789'  # without 0, 1
ALPHABET_BASE56 = ALPHABET_LOWERCASE_BASE56 + ALPHABET_UPPERCASE_BASE56 + DIGITS_BASE56

ALPHABET_LOWERCASE_BASE58 = 'abcdefghijkmnopqrstuvwxyz'  # without l, o
ALPHABET_UPPERCASE_BASE58 = 'ABCDEFGHJKLMNPQRSTUVWXYZ'  # without I, O
DIGITS_BASE58 = '123456789'  # without 0
ALPHABET_BASE58 = ALPHABET_LOWERCASE_BASE58 + ALPHABET_UPPERCASE_BASE58 + DIGITS_BASE58
