name: Release Pipeline

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release Pipeline
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: 🔖 Semantic Release
        uses: python-semantic-release/python-semantic-release@1a324000f2251a9e722e77b128bf72712653813f
        with:
          build: false
          push: true
          changelog: true
          commit: true
          tag: true
          vcs_release: true
          config_file: pyproject.toml
          git_committer_email: ${{ vars.GIT_COMMITTER_EMAIL }}
          git_committer_name: ${{ vars.GIT_COMMITTER_NAME }}
          github_token: ${{ secrets.PAT_WITH_REPOSITORY_WRITE }}
          ssh_public_signing_key: ${{ vars.SSH_PUBLIC_SIGNING_KEY }}
          ssh_private_signing_key: ${{ secrets.SSH_PRIVATE_SIGNING_KEY }}
